# Generated by Django 3.2.4 on 2021-07-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='baner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
