# Generated by Django 3.2.4 on 2021-08-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mymessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='baner',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
