# Generated by Django 3.2.4 on 2021-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_baner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='baner',
            field=models.ImageField(blank=True, default='defaultimages/default.png', null=True, upload_to=''),
        ),
    ]
