# Generated by Django 3.2.4 on 2021-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_baner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cont', models.CharField(max_length=200)),
                ('baner_link', models.CharField(max_length=300)),
            ],
        ),
    ]
