# Generated by Django 3.2.4 on 2021-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_jumbotron'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumbotron',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('none', 'none')], default='none', max_length=10),
        ),
    ]
